name: Build Box64 for AArch64

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on AArch64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build using QEMU AArch64
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
          sudo apt update
          sudo apt install -y cmake gcc g++ git
          git clone https://github.com/ptitSeb/box64.git
          mkdir box64/build && cd box64/build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
          make -j$(nproc)

    - name: Upload Box64 binary
      uses: actions/upload-artifact@v3
      with:
        name: box64-aarch64
        path: box64/build/box64
