name: Rust

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [ 'stable' ]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust ${{ matrix.rust-version }}
        uses: actions/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}
      - name: Display Rust version
        run: rustc --version
